### BOW >>>>>>>>>>>>>>> Bag of word  

In [1]:
import pandas as pd 

In [2]:
text = {"text":["People watch Aiyug","Aiyug watch Aiyug","People write comment ","Aiyug write comment"],"Output":[1,1,0,0] }
data =pd.DataFrame(text)
data


text  Output
0     People watch Aiyug       1
1      Aiyug watch Aiyug       1
2  People write comment        0
3    Aiyug write comment       0

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
cv  = CountVectorizer(lowercase=True,stop_words="english",binary=True)

In [36]:
bow =cv.fit_transform(data['text'])

In [37]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'aiyug': 0, 'write': 4, 'comment': 1}

In [38]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())


[[1 0 1 1 0]]
[[1 0 0 1 0]]
[[0 1 1 0 1]]
[[1 1 0 0 1]]


In [39]:
cv.transform(["Comment is good student and Comment is student to jaipur  "]).toarray()

array([[0, 1, 0, 0, 0]], dtype=int64)