### BOW >>>>>>>>>>>>>>> Bag of word  

In [1]:
import pandas as pd 

In [2]:
text = {"text":["People watch Aiyug","Aiyug watch Aiyug","People write comment ","Aiyug write comment"],"Output":[1,1,0,0] }
data =pd.DataFrame(text)
data


text  Output
0     People watch Aiyug       1
1      Aiyug watch Aiyug       1
2  People write comment        0
3    Aiyug write comment       0

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
cv  = CountVectorizer(lowercase=True,stop_words="english",binary=True)

In [36]:
bow =cv.fit_transform(data['text'])

In [37]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'aiyug': 0, 'write': 4, 'comment': 1}

In [38]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())


[[1 0 1 1 0]]
[[1 0 0 1 0]]
[[0 1 1 0 1]]
[[1 1 0 0 1]]


In [39]:
cv.transform(["Comment is good student and Comment is student to jaipur  "]).toarray()

array([[0, 1, 0, 0, 0]], dtype=int64)

### N grams 

In [1]:
from nltk.util import ngrams
from nltk.tokenize import word_tokenize

text = "I love natural language processing"
tokens = word_tokenize(text)  # Tokenize into words

n = 2  # Set the N for N-grams (bigrams in this case)
bigrams = list(ngrams(tokens, n))

print(bigrams)


[('I', 'love'), ('love', 'natural'), ('natural', 'language'), ('language', 'processing')]


### Td-Idf

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

documents = [
    "I love natural language processing",
    "Deep learning is great for NLP",
    "TF-IDF is useful in text mining"
]

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)
# print(tfidf_matrix)

# Print TF-IDF scores
feature_names = vectorizer.get_feature_names_out()   ### get 
# print(feature_names)
for doc_idx, doc in enumerate(tfidf_matrix.toarray()):
    print(f"Document {doc_idx+1}:")
    for word_idx, score in enumerate(doc):
        if score > 0:
            print(f"  {feature_names[word_idx]}: {score:.4f}")
# 

Document 1:
  language: 0.5000
  love: 0.5000
  natural: 0.5000
  processing: 0.5000
Document 2:
  deep: 0.4234
  for: 0.4234
  great: 0.4234
  is: 0.3220
  learning: 0.4234
  nlp: 0.4234
Document 3:
  idf: 0.3899
  in: 0.3899
  is: 0.2965
  mining: 0.3899
  text: 0.3899
  tf: 0.3899
  useful: 0.3899
